auto: false
name: Will Landau
description: I am a Statistics PhD candidate at Iowa State University. My research interests include statistical computing and statistical genomics. I received my Bachelor of Science in Mathematics from the University of Chicago in 2011. I do martial arts in my spare time, and I also like to sail and climb.
url: http://will-landau.com